### ISSUE TITLE
deb package missing standard field

### ISSUE THREAD

**Issue by ftoledo** [mkrueger/icy_term#10]
ragnarok@ragnarok:/tmp$ sudo dpkg -i icy_term_0.4.2_amd64.deb 
dpkg: atención: parsing file '/var/lib/dpkg/tmp.ci/control' near line 8 package 'icy-term':
 missing 'Maintainer' field
Seleccionando el paquete icy-term previamente no seleccionado.
(Leyendo la base de datos ... 756975 ficheros o directorios instalados actualmente.)
Preparando para desempaquetar icy_term_0.4.2_amd64.deb ...

**Comment by mkrueger** [comment]
Worked on build pipeline & fixed that issue.
