### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by bharrisii** [mkrueger/icy_term#11]
Trying to compile runs though and will error out:

MacOS Ventura 13.5
rustc 1.71.1 (eb26296b5 2023-08-03)
cargo 1.71.1 (7f1d04c00 2023-07-29)

Output:
<snip>
 Compiling icy_term v0.5.0 (/Users/xxxxxx/Downloads/icy_term/icy_term)
error[E0599]: no method named `from_unicode` found for struct `Box<(dyn BufferParser + 'static)>` in the current scope
   --> src/ui/main_window_mod.rs:227:50
    |
227 |         let translated_char = self.buffer_parser.from_unicode(ch);
    |                                                  ^^^^^^^^^^^^ help: there is a method with a similar name: `convert_from_unicode`

error[E0599]: no method named `from_unicode` found for struct `Box<(dyn BufferParser + 'static)>` in the current scope
   --> src/ui/main_window_mod.rs:242:58
    |
242 |                 let translated_char = self.buffer_parser.from_unicode(ch);
    |                                                          ^^^^^^^^^^^^ help: there is a method with a similar name: `convert_from_unicode`

error[E0599]: no method named `from_unicode` found for struct `Box<(dyn BufferParser + 'static)>` in the current scope
   --> src/ui/main_window_mod.rs:249:58
    |
249 |                 let translated_char = self.buffer_parser.from_unicode(ch);
    |                                                          ^^^^^^^^^^^^ help: there is a method with a similar name: `convert_from_unicode`

error[E0599]: no method named `from_unicode` found for struct `Box<(dyn BufferParser + 'static)>` in the current scope
   --> src/ui/main_window_mod.rs:496:42
    |
496 |         let mut cr = [self.buffer_parser.from_unicode('\r') as u8].to_vec();
    |                                          ^^^^^^^^^^^^ help: there is a method with a similar name: `convert_from_unicode`

error[E0599]: no method named `to_unicode` found for reference `&dyn BufferParser` in the current scope
   --> src/ui/buffer_view/mod.rs:533:44
    |
533 |                     res.push(buffer_parser.to_unicode(ch.ch));
    |                                            ^^^^^^^^^^ help: there is a method with a similar name: `convert_to_unicode`

error[E0599]: no method named `to_unicode` found for reference `&dyn BufferParser` in the current scope
   --> src/ui/buffer_view/mod.rs:546:44
    |
546 |                     res.push(buffer_parser.to_unicode(ch.ch));
    |                                            ^^^^^^^^^^ help: there is a method with a similar name: `convert_to_unicode`

error[E0599]: no method named `to_unicode` found for reference `&dyn BufferParser` in the current scope
   --> src/ui/buffer_view/mod.rs:551:44
    |
551 |                     res.push(buffer_parser.to_unicode(ch.ch));
    |                                            ^^^^^^^^^^ help: there is a method with a similar name: `convert_to_unicode`

error[E0599]: no method named `to_unicode` found for reference `&dyn BufferParser` in the current scope
   --> src/ui/buffer_view/mod.rs:557:48
    |
557 |                         res.push(buffer_parser.to_unicode(ch.ch));
    |                                                ^^^^^^^^^^ help: there is a method with a similar name: `convert_to_unicode`

error[E0599]: no method named `to_unicode` found for reference `&dyn BufferParser` in the current scope
   --> src/ui/buffer_view/mod.rs:563:44
    |
563 |                     res.push(buffer_parser.to_unicode(ch.ch));
    |                                            ^^^^^^^^^^ help: there is a method with a similar name: `convert_to_unicode`

error[E0599]: no function or associated item named `new` found for struct `PETSCIIParser` in the current scope
   --> src/ui/screen_modes.rs:112:69
    |
112 |                 main_window.buffer_parser = Box::new(PETSCIIParser::new());
    |                                                                     ^^^ function or associated item not found in `PETSCIIParser`

error[E0599]: no function or associated item named `new` found for struct `AtasciiParser` in the current scope
   --> src/ui/screen_modes.rs:122:69
    |
122 |                 main_window.buffer_parser = Box::new(AtasciiParser::new());
    |                                                                     ^^^ function or associated item not found in `AtasciiParser`

error[E0599]: no function or associated item named `new` found for struct `PETSCIIParser` in the current scope
   --> src/address_mod.rs:160:48
    |
160 |                 return Box::new(PETSCIIParser::new());
    |                                                ^^^ function or associated item not found in `PETSCIIParser`

error[E0599]: no function or associated item named `new` found for struct `AtasciiParser` in the current scope
   --> src/address_mod.rs:163:48
    |
163 |                 return Box::new(AtasciiParser::new());
    |                                                ^^^ function or associated item not found in `AtasciiParser`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `icy_term` (bin "icy_term") due to 13 previous errors

**Comment by ftoledo** [comment]
same issue on debian 11.x with rust 1.71

**Comment by mkrueger** [comment]
I updated one underlying library.
Fixed.
