### ISSUE TITLE
Crashes when connecting

### ISSUE THREAD

**Issue by bharrisii** [mkrueger/icy_term#13]
Launches fine.  Program crashes when connecting to site in address book.  

$ RUST_BACKTRACE=full ./icy_term
thread 'main' panicked at 'internal error: entered unreachable code', /Users/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/poll-promise-0.2.0/src/promise.rs:332:49
stack backtrace:
   0:        0x10f37a743 - __mh_execute_header
   1:        0x10f398d3b - __mh_execute_header
   2:        0x10f376e88 - __mh_execute_header
   3:        0x10f37a53a - __mh_execute_header
   4:        0x10f37b985 - __mh_execute_header
   5:        0x10f37b78f - __mh_execute_header
   6:        0x10f37be23 - __mh_execute_header
   7:        0x10f37bd02 - __mh_execute_header
   8:        0x10f37ab49 - __mh_execute_header
   9:        0x10f37ba7d - __mh_execute_header
  10:        0x10f3cbd33 - __mh_execute_header
  11:        0x10f3cbdc7 - __mh_execute_header
  12:        0x10ee4a83a - __mh_execute_header
  13:        0x10eeec2c7 - __mh_execute_header
  14:        0x10f1f278f - __mh_execute_header
  15:        0x10f1fbbcf - __mh_execute_header
  16:        0x10f1ead83 - __mh_execute_header
  17:        0x10f1f4229 - __mh_execute_header
  18:        0x10f2954e8 - __mh_execute_header
  19:        0x10f2971b7 - __mh_execute_header
  20:        0x10f29175f - __mh_execute_header
  21:     0x7ff80d4c3444 - <unknown>
  22:     0x7ff80d4c336b - <unknown>
  23:     0x7ff80d4c2a17 - <unknown>
  24:     0x7ff80d4c1f31 - <unknown>
  25:     0x7ff816f42f3d - <unknown>
  26:     0x7ff816f42d4e - <unknown>
  27:     0x7ff816f42aa8 - <unknown>
  28:     0x7ff81055e25c - <unknown>
  29:     0x7ff81055d106 - <unknown>
  30:     0x7ff81054f788 - <unknown>
  31:        0x10f1e9120 - __mh_execute_header
  32:        0x10f1f8bb7 - __mh_execute_header
  33:        0x10f1fe562 - __mh_execute_header
  34:        0x10f1e6b27 - __mh_execute_header
  35:        0x10eedca2a - __mh_execute_header
  36:        0x10ee35a5f - __mh_execute_header
  37:        0x10ee528cf - __mh_execute_header
  38:        0x10ee52c16 - __mh_execute_header
  39:        0x10eef83cc - __mh_execute_header
  40:        0x10f37200a - __mh_execute_header
  41:        0x10ee52a2c - __mh_execute_header
  42:     0x7ff80d08e41f - <unknown>

**Comment by mkrueger** [comment]
Which operating system?

**Comment by mkrueger** [comment]
Using poll promise from github should fix the issue.

**Comment by bharrisii** [comment]
Looks like that took care of the issue.
