### ISSUE TITLE
No Control Key at C64 Mode?

### ISSUE THREAD

**Issue by soenkesmiletzki** [mkrueger/icy_term#14]
How to use the Control Key at C64 Mode?

I have to press Control + A or Control + Z at my BBS to use some special commands.

**Comment by mkrueger** [comment]
Can I access the bbs somehow for testing?

**Comment by soenkesmiletzki** [comment]
ok, try it:
rapidfire.hopto.org:64128
user and pw: test

and by the way: please check the filetransfer (downloads), because it doesn't work :-(

**Comment by soenkesmiletzki** [comment]
I try filetransfer on three other c64 boards and none works :-(

**Comment by mkrueger** [comment]
all my file transfer unit tests broke at some point - when I switched to tokio for communication. 

At least z-modem seems to work. I'll take a look at that.

ty for testing the C64 support. Was my 2nd computer.

**Comment by mkrueger** [comment]
Control codes should work in 0.5.2 - took the values from the C64 wiki.

Didn't check the protocols yet but it's on my todo list.

**Comment by soenkesmiletzki** [comment]
Mh, how to use Ctrl Keys on OSX?

Oh, auch deutsch :-) Sehr gut...
