### ISSUE TITLE
FILE_ID.DIZ plz?

### ISSUE THREAD

**Issue by Paulie420** [mkrueger/icy_term#2]
No biggy and super glad to see Icy Term getting dev attention;
can you add a FILE_ID.DIZ release archives? 
http://www.textfiles.com/artscene/information/faq-file_id.html
As long as its in the first / directory of the ZIP/TAR, bbSes could display detailed info about Icy, or whats in this release update, etc...

**Comment by mkrueger** [comment]
Added a file_id.diz to the 0.2.5 release thought that I'm a bit faster with 0.3.0 but it'll take longer than expected :/.
