### ISSUE TITLE
Z-Modem Download Fails with PD-Zmodem

### ISSUE THREAD

**Issue by Renegade-Exodus** [mkrueger/icy_term#21]
![image](https://github.com/mkrueger/icy_term/assets/3454547/3fcdd09e-3bb8-44a2-9401-70a535e7c2e8)

As soon as download is started this screen shows and then freezes.

**Comment by mkrueger** [comment]
ATM I investigate a refactoring on the communication layer. I'll look at it. 
Z-Modem can be a bit tricky to implement correctly. There are many variants out there.

**Comment by mkrueger** [comment]
Update: I got the down & upload working again :). Just called your BBS 1000 +- 5 times.

But it's not ready yet - I need to work on the UI I broke it with my refactorings and I need to rework it a bit. Up & Downloading in the web is not much of an issue these days. Uploading & Downloading in a BBS is an experience.
