### ISSUE TITLE
exit on OSX doesn't work

### ISSUE THREAD

**Issue by soenkesmiletzki** [mkrueger/icy_term#22]
I couldn't close the APP without OSX Error "Icy Term wurde unerwartet beendet" and three Buttons like "Erneut öffnen", "Melden..." and "Ignorieren".

System: Macbook Pro M1
MacOS: Ventura 13.4.1 (c)

**Comment by soenkesmiletzki** [comment]
`soenke.smiletzki@mbp-soenke /Applications % ./Icy\ Term.app/Contents/MacOS/icy_term
unsupported control code 21
unsupported control code 21
error while sending: channel closed
zsh: trace trap  ./Icy\ Term.app/Contents/MacOS/icy_term
soenke.smiletzki@mbp-soenke /Applications % `

**Comment by mkrueger** [comment]
I've implemented proper logging for the native opengl calls. Not yet ready for a next release. 
I need to clean up a lot :(

**Comment by mkrueger** [comment]
Released 0.6.0 today & fixed a lot of opengl calls. Can you try the 0.6.0 release? Thanks

**Comment by soenkesmiletzki** [comment]
> Released 0.6.0 today & fixed a lot of opengl calls. Can you try the 0.6.0 release? Thanks

yes, works fine... exit without error

**Comment by mkrueger** [comment]
Ok then I blame one of the opengl bugs I fixed. I had plenty of them - however drawing worked, I didn't look at opengl status before :/.
