### ISSUE TITLE
Top of screen missing.

### ISSUE THREAD

**Issue by leenooks** [mkrueger/icy_term#33]
Howdy,

I'm running icyterm on a Mac (Silicon) - and in both videotex and ansi modes, the top of the screen is missing:

(I was using 0.4.1(?) before and it was working great...)

<img width="1042" alt="Screenshot 2023-08-26 at 10 04 48 am" src="https://github.com/mkrueger/icy_term/assets/131527/6a463e82-4018-4476-a64b-ac1e2ad6a2f8">

**Comment by mkrueger** [comment]
y had a problem in mac builds - will re-upload them when the build is finished.

**Comment by mkrueger** [comment]
fixed the 0.6.2 builds - should've double checked them :/.
