### ISSUE TITLE
Problem launching 0.6.3 in macOS

### ISSUE THREAD

**Issue by cmang** [mkrueger/icy_term#36]
Ventura 13.2.1, ARM64 cpu. I downloaded the file: icy_term_osx_0.6.3_aarch64-apple-darwin.zip

If I try to launch the app icon, it bounces once and stops.

Digging into the app bundle, there seems to be a problem running the binary executable:

% pwd
/Applications/Icy Term.app/Contents/MacOS

% ./icy_term
[2023-08-28T06:16:23Z ERROR icy_term::ui::app] Error reading dialing_directory: Error parsing dialing_directory: TOML parse error at line 54, column 24
       |
    54 | comment = "ENiGMA½ WHQ""
       |                        ^
    expected newline, `#`

thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/ui/dialogs/dialing_directory_dialog.rs:56:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by mkrueger** [comment]
Should've tried on a clean install :/ - the change in the  default dialing directory is new but not THAT new :(.

/fixed

https://github.com/mkrueger/icy_term/releases/latest
