### ISSUE TITLE
ZMODEM Downloads

### ISSUE THREAD

**Issue by dmine45** [mkrueger/icy_term#39]
ZModem downloads are not working on version 0.6.5 (Windows).

**Comment by mkrueger** [comment]
Just tested - works for me. Which bbs? 

There are several z modem variants, it may be that I'm missed one.

**Comment by dmine45** [comment]
Diamond Mine Online. Bbs.dmine.net port 24.
Thanks!

Sent from Yahoo Mail on Android 
 
  On Thu, Aug 31, 2023 at 10:43 AM, Mike ***@***.***> wrote:   


Just tested - works for me. Which bbs?

There are several z modem variants, it may be that I'm missed one.

**Comment by mkrueger** [comment]
ty I'll take a look.

**Comment by mkrueger** [comment]
BBS was online today :)
Should be fixed.
