### ISSUE TITLE
Crash on Wine

### ISSUE THREAD

**Issue by qarmin** [mkrueger/icy_term#4]
Cannot run on wine-stagins 7.22 due this error 
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', src\ui\edit_bbs.rs:23:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by mkrueger** [comment]
Should be fixed by

https://github.com/mkrueger/icy_term/commit/2ea1dedacf1d1b14625abbe1422579e9ce09a12d
and https://github.com/mkrueger/icy_term/commit/d2efda96439a8ac66543df956f82436be4e49ef8
