### ISSUE TITLE
Ansimation not rendering correctly...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_term#40]
My third bulletin screen (using catfade) renders it's exit animation properly from ftelnet, but not icyterm.  It's hard to describe, I believe it deletes from the outside in.

**Comment by martykazmaier** [comment]
https://shsbbs.net/bbs.html or ssh to shsbbs.net (bbs:shsbbs login:pass, then emsi login). or telnet shsbbs.net.

**Comment by martykazmaier** [comment]
115,200 rendering speed.  Either the third bulletin screen with the full login sequence, or the 3rd news bulletin screen from the stats page.

**Comment by mkrueger** [comment]
Do you mean the "fading news"?

**Comment by martykazmaier** [comment]
Yes.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by martykazmaier** [comment]
Only the third bulletin's animation isn't rendering properly.

**Comment by martykazmaier** [comment]
Odd.  It appears to work windowed, but not full screened.

**Comment by mkrueger** [comment]
ah ok I'll try again because it seemed to work for me :) - but I'm working on a newer version with a slightly improved rendering enigne. My next project has very high requirements in that regard.

**Comment by martykazmaier** [comment]
Thanks.  I think that the third bulletin may not always animate.  I could slow it down further in the settings, but the first 2 work fine.  I tried ftelnet again and it was the same.  Not always animated.  I think I may have over reacted, and it may have nothing to do with icyterm.
