### ISSUE TITLE
Filetransfer with a real C64 BBS failed

### ISSUE THREAD

**Issue by soenkesmiletzki** [mkrueger/icy_term#43]
Sorry, but no filetransfer with a real c64 bbs is working :-(
I try it with xmodem, xmodem1k and xmodem-crc, but it doesn't work :-(

**Comment by mkrueger** [comment]
y I really neeed to look at the file transfer protocols :/

**Comment by soenkesmiletzki** [comment]
contact me via facebook for getting help.

**Comment by mkrueger** [comment]
Fixed the issue.
