### ISSUE TITLE
Win10 Opening issues

### ISSUE THREAD

**Issue by Renegade-Exodus** [mkrueger/icy_term#44]
Cannot open latest version in Win10 x64.   Click on file, and nothing happens.  Same with Icy View.  Would like a 32 bit version in the future if possible.

**Comment by mkrueger** [comment]
Can you open in the command line? Sounds like graphics cant initialize.

**Comment by Renegade-Exodus** [comment]
Nothing, just falls back to the prompt. :(  Just using the onboard video.
Program worked before 0.6.5 ...

**Comment by mkrueger** [comment]
Windows seems to hide std out 
can you try to:
SET RUST_LOG="icy_term=INFO,icy_engine=INFO"
icy_term.exe

if that still don't work mabye routing std to a file gives some more info
icy_term.exe >out.txt

I'll put proper logging on my todo list - currently working on a bigger tool where I implemented proper file logging. I'll backport that to icy_term/icy_view

**Comment by Renegade-Exodus** [comment]
Will do when I get home.  Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Renegade-Exodus** [comment]
Neither worked.  Trying to force output to a text file just created a blank
text file.   The "set" command didn't write anything to that directory
after I ran icy_term. :(

**Comment by Renegade-Exodus** [comment]
I just downloaded 0.2.5 again to see if it wasn't just this computer and it opens up fine.  0.6.4 did not load tho.  Somewhere between 0.2.5 and 0.6.4 something broke. :(

**Comment by mkrueger** [comment]
0.2.5 didn't require working 3d graphics. It may be that I switched OGL version to something different that may not be supported.

Did 0.5-0.6 work ?

**Comment by mkrueger** [comment]
Added logging - will release 0.6.6 today. Will fix another bug. 
Log file will be in:
C:\Users\<USERNAME>\AppData\Roaming\GitHub\icy_term\config

**Comment by Renegade-Exodus** [comment]
I can't find that ver ... got a link?

**Comment by mkrueger** [comment]
https://github.com/mkrueger/icy_term/releases/tag/0.6.6

**Comment by Renegade-Exodus** [comment]
![image](https://github.com/mkrueger/icy_term/assets/3454547/700b31ed-3f81-4825-84e0-cbc47a31ab9d)
No go on 32bit Windows.

**Comment by Renegade-Exodus** [comment]
0.6.6 --- 64bit still won't open to run. :(

**Comment by mkrueger** [comment]
As suspected - I only added logging.

Anything in the log file? 

 C:\Users\<USERNAME>\AppData\Roaming\GitHub\icy_term\config

**Comment by Renegade-Exodus** [comment]
INFO - Starting iCY TERM 0.6.6
INFO - Current Locale: [LanguageIdentifier { language:
Language(Some("en")), script: None, region: Some(Region("US")), variants:
None }]
WARN - You forgot to call destroy() on the egui glow painter. Resources
will leak!
INFO - Starting iCY TERM 0.6.6
INFO - Current Locale: [LanguageIdentifier { language:
Language(Some("en")), script: None, region: Some(Region("US")), variants:
None }]
WARN - You forgot to call destroy() on the egui glow painter. Resources
will leak!
INFO - Starting iCY TERM 0.6.6
INFO - Current Locale: [LanguageIdentifier { language:
Language(Some("en")), script: None, region: Some(Region("US")), variants:
None }]
WARN - You forgot to call destroy() on the egui glow painter. Resources
will leak!
INFO - Starting iCY TERM 0.6.6
INFO - Current Locale: [LanguageIdentifier { language:
Language(Some("en")), script: None, region: Some(Region("US")), variants:
None }]
WARN - You forgot to call destroy() on the egui glow painter. Resources
will leak!
INFO - Starting iCY TERM 0.6.6
INFO - Current Locale: [LanguageIdentifier { language:
Language(Some("en")), script: None, region: Some(Region("US")), variants:
None }]
WARN - You forgot to call destroy() on the egui glow painter. Resources
will leak!

**Comment by mkrueger** [comment]
Now I'm running out of ideas.

The only thing that might help is a debug build wit symbols - unfortunately that needs to be build on the machine it runs on. 

There are two requirements: 

Getting rust:
https://doc.rust-lang.org/cargo/getting-started/installation.html

Download the icy_term git and run "cargo run" in that directory.

That should work. However it may be that some developer dependencies are required. I don't build on windows myself and even then I would've developer dependencies.
Perl may be required by openssh for building/getting the libraries (https://www.perl.org/get.html)

That should work then. If not I can guide you through maybe with discord? (.agwen)

**Comment by mkrueger** [comment]
I've a report from icy draw with a debug build:

```
C:\Users\bbs\Downloads\icy_draw-debug-build-win32>icy_draw.exe
2023-10-15T14:32:36.873636200-04:00 INFO icy_draw - Starting iCY DRAW 0.1.0
2023-10-15T14:32:36.988341900-04:00 ERROR eframe::native::run::glow_integration - failed to set swap interval due to error: Error { raw_code: None, raw_os_message: None, kind: NotSupported("swap contol extrensions are not supported") }
thread 'main' panicked at 'An OpenGL error occurred: egui_glow requires opengl 2.0+.
```

Seems that some machines  don't have opengl installed - which is an requirement.

Maybe it's the vc runtime missing (unlikely should be shipped in win10):
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by nolageek** [comment]
Any change you can support older versions of OpenGL? Graphics card on my BBS server only supports OpenGL 1.x
