### ISSUE TITLE
vicII + petscii issues when typing shift+number

### ISSUE THREAD

**Issue by Grrrolf** [mkrueger/icy_term#45]
Hello, 
I noticed that there's an issue when typing shift + number to get the signs like !, %, $, etc.
See this screenshot:

<img width="1404" alt="image" src="https://github.com/mkrueger/icy_term/assets/10052794/e2835816-c979-44fb-8c20-8cad8df12c97">

First line: the number, second line: shift + number.
This behaviour severely impacts the user experience. Especially when any of those chars are used in the password.

**Comment by mkrueger** [comment]
Should be fixed - hard to get the correct keymap :(
