### ISSUE TITLE
Zmodem uploads from win 10 dialog issue

### ISSUE THREAD

**Issue by wx4cb** [mkrueger/icy_term#47]
when i start the upload process on my synchro bbs, and i click the "upload" button iin the tool bar... it takes me to "c:\windows\system32".

no biggie, i can navigate from there .... EXCEPT, every time the bbs sends the header, it goes back to that directory and then you have to try and navigate again... kinda awkward when it happens every 5 seconds.

when ii finally managed to get it to try and upload something but it wouldnt go through. but the main thing is the dialog box change on header reception

**Comment by mkrueger** [comment]
Not sure if I understood the problem correctly but I think I fixed it.

**Comment by wx4cb** [comment]
> Not sure if I understood the problem correctly but I think I fixed it.

basically if you had the file chooser dialog open to pick a file for an upload, every time the term got the ZModem header, it would change the path ini the dialog back to c:\windows\system32 and of course that happens every 5 seconds when the header comes in :D

i'll take a look when i get back home and let you know.
