### ISSUE TITLE
Tab key UI issue

### ISSUE THREAD

**Issue by cognitivegears** [mkrueger/icy_term#49]
When connected to a BBS, pressing the TAB key on the terminal (to switch fields on a BBS,) results in both the tab being sent to the BBS (like it should) as well as highlighting the Upload button. Then, when a user hits <Enter> on the BBS, it actually triggers the Upload button, bringing up the "Select Upload protocol."

I would suggest that these menu buttons not be allowed to get tab focus (though hotkeys would be nice for them) so that it does not interrupt when trying to log into a BBS. Xibalba (xibalba.l33t.codes:44510) is an example of a BBS that is affected by this, as the login sequence makes heavy use of TAB and Enter to navigate.

Version: iCY TERM 0.5.3

**Comment by mkrueger** [comment]
Try to update to 0.6.6 - tab key should be fixed.
