### ISSUE TITLE
Features: UI improvements on Dialing Directory

### ISSUE THREAD

**Issue by cognitivegears** [mkrueger/icy_term#50]
Thank you for making icy_term. It is already my favorite BBS client, and I have a feeling your just getting started! I know you have a lot of other things, but below are a couple of small "quality of life" improvements that would be nice for the Dialing Directory:

* This is a small item, but it would be great if hitting enter after entering a hostname:port in the <Connect to Address> would automatically connect rather than having to click the Connect button.
* When hitting the + sign and creating a new entry, on the left pane the name is white on a very light grey, and barely shows up on my display. And until you enter an address, there is no line below it to show the entry, so new entries look almost invisible. Another color besides white for the title may help make this be a little more obvious (even better may be two different colors for existing entries vs "New BBS")

**Comment by mkrueger** [comment]
Arrow keys + return will be working in the next version.

**Comment by cognitivegears** [comment]
Confirmed I was just using an old version, the theming is much better with this version, thanks! Looking forward to the arrow keys/return will be great, thank you!

**Comment by mkrueger** [comment]
just released 0.6.7 :)
