### ISSUE TITLE
ctrl-]

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_term#51]
Doesn't seem to work.  I need to use it when I'm telnetting out from a system to disconnect if things to awry.

**Comment by mkrueger** [comment]
Update on this - need a change in the UI lib I use they didn't map the '[' key and some others I missed.

I opened a PR on that https://github.com/emilk/egui/pull/3373

I would prefer having that change in their main branch. I've some libraries with egui dependencies and using a custom branch would require me to fork them all. (Which I'll do if the PR merge takes too long)

**Comment by mkrueger** [comment]
argh they updated egui to 0.23 but my fix didn't make it in… still looking at that.

If they don't do it in 0.24 I'll fork.

**Comment by mkrueger** [comment]
Got merged this week in egui - took a lot longer than expected :/. Had too many deps to egui forking that was too much effort :(.

Will be fixed in the next version (0.6.9).
