### ISSUE TITLE
Invisible Cursor...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_term#52]
I just tried to respond to a message and there was no cursor to show me where I was typing.  Not sure if this was normal or not.  .6.6

**Comment by mkrueger** [comment]
It's possible for ansi sequences to turn the cursor off.

I need more context here. Which bbs? Is it reproducible?

**Comment by martykazmaier** [comment]
Any BBS.  Shsbbs.net for example, in ice edit.  Every time.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by mkrueger** [comment]
released 0.6.7 - could be that I broke it in 0.6.6 - I've worked on the caret display code a bit.

**Comment by mkrueger** [comment]
I think I've a repro case - looking at it.

**Comment by mkrueger** [comment]
I silently updated the 0.6.7 build with the fix - there aren't many DLs.

**Comment by martykazmaier** [comment]
I got it, thanks.  Now zmodem downloads seem broken, or I don’t know where they’re going.  They’re not going to c:\users\username\downloads.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
