### ISSUE TITLE
Feature: 40 column / Wide column

### ISSUE THREAD

**Issue by cognitivegears** [mkrueger/icy_term#53]
I would love to see a 40 column mode for icy_term, as well as wide terminal support. Maybe settings like:
40x25
132x37 (16:9)
132x52 (5:4)
132x25

(along with maybe others?)

I have to admit I have a unique use case for this, as I'm doing testing on the Enigma BBS software for alternate screen dimensions, and would love to have another terminal with 40 column and wide term support, though I could see this useful for other people as well, especially with the wide terminal mode.

Thanks for the consideration!

**Comment by mkrueger** [comment]
I can allow custom settings. Adding more to the list feels wrong.

**Comment by mkrueger** [comment]
0.6.8 fixes that.
