### ISSUE TITLE
Shift-arrow keys...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_term#58]
Doesn't work.  Unfortunately, I do that a lot...  It doesn't do anything, at least on my bbs:  shsbbs.net.

**Comment by mkrueger** [comment]
Should've been fixed in 0.6.7 - didn't close that issue. 
(will release 0.6.8 soon)

**Comment by martykazmaier** [comment]
The appear as special characters now, not arrow keys.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by martykazmaier** [comment]
Nevermind, it’s working now.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
