### ISSUE TITLE
.6.7 totally breaks zmodem downloads...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_term#59]
shsbbs.net, I can't download from any of my download apps (OLMS2000, the reader or nodeview 2.10) or the files area download protocols.  It just dumps straight out of the download to a garbage full screen.

**Comment by mkrueger** [comment]
fixed the zmodem for synchronet - maybe that had side effects. I'll take a look.

**Comment by mkrueger** [comment]
Found it - I broke zmodem unit tests because I moved it to another layer. I'll put some work in it to reactivate the unit tests.

**Comment by mkrueger** [comment]
0.6.8 fixes that.
