### ISSUE TITLE
copy/paste weirdness...

### ISSUE THREAD

**Issue by martykazmaier** [mkrueger/icy_term#60]
Copy buffer doesn't end up in main copy/paste location.  I can't copy/paste from icyterm to host or host to icyterm.

**Comment by mkrueger** [comment]
Works for me which OS and which icy term version?

**Comment by martykazmaier** [comment]
Windows 10, Icyterm 6.7.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by mkrueger** [comment]
0.6.8 fixes that.
