### ISSUE TITLE
Screen sizing issue

### ISSUE THREAD

**Issue by leenooks** [mkrueger/icy_term#7]
Howdy, I'm using 0.4.0, and it seems that the terminal only uses 1/4 of the space (and thus is quite small).

I'm on a MAC - see the pics:
<img width="1392" alt="Screenshot 2023-02-19 at 9 33 07 am" src="https://user-images.githubusercontent.com/131527/219902413-b2c3f829-b9a3-4346-96c1-e2da88dc3989.png">
<img width="1392" alt="Screenshot 2023-02-19 at 9 32 31 am" src="https://user-images.githubusercontent.com/131527/219902419-c170684d-e068-4d4d-90de-5e046e0b0216.png">

**Comment by mkrueger** [comment]
Finally could reproduce it - I only needed a high resolution monitor.

**Comment by leenooks** [comment]
Thanks for fixing this, will you be providing updated builds?
