### ISSUE TITLE
Feature Request: Notify user when the connection is closed/disconnected

### ISSUE THREAD

**Issue by dmine45** [mkrueger/icy_term#70]
It would be nice to let the user know when the telnet connection has ended/disconnected. Most programs do this. Please add this feature to the program if you can. Thanks!

**Comment by mkrueger** [comment]
Title bar should show disconnected when it disconnects.

However I added a dialog which improves the experience. I'll release 0.7.0 in a few days. Need to fix mac builds - something broke in the pipeline.
