### ISSUE TITLE
Gap too large between RIP and text

### ISSUE THREAD

**Issue by rexhondo** [mkrueger/icy_term#73]
Here are a few examples. The empty space should not be there. The text should appear immediately below the RIP. RIPterm and SyncTerm both render this properly.
![image](https://github.com/mkrueger/icy_term/assets/60751127/ff6c0db0-2165-451b-a158-5cb8d1755d2f)
![image](https://github.com/mkrueger/icy_term/assets/60751127/efd1845e-d983-42cd-8af0-5d88b9638129)
![image](https://github.com/mkrueger/icy_term/assets/60751127/1d654b2a-85c8-4786-9e96-69a228962f24)
The red box on the screenshots indicate the area that should not be blank.

**Comment by mkrueger** [comment]
0.7.3 should fix it. I think I fixed that issue in 0.7.2 and updated the release.

![grafik](https://github.com/mkrueger/icy_term/assets/341098/28e4cc8f-9f13-49de-85f5-969f36efdd0f)

![grafik](https://github.com/mkrueger/icy_term/assets/341098/35affd17-adb9-4113-998e-00941186bc88)
