### ISSUE TITLE
CTRL-X does not work with Icy Term

### ISSUE THREAD

**Issue by AppleSeedTrees** [mkrueger/icy_term#74]
A bunch of BBS require the CTRL-X and it is now working, at least with the Windows version of Icy Term. I tried it on two separate machines and no luck.

**Comment by mkrueger** [comment]
Latest ui lib update broke it they just throw features in the ui lib without thinking about the implications :/.

https://github.com/emilk/egui/issues/4065

However I can do a work around for this behavior.
